library(network)
library(sna)
library(ggplot2)
library(ggnetwork)
library(cowplot)
library(GGally)

n <- network(rgraph(15, tprob = 0.1), directed = FALSE)
set.seed(1)
##n %v% "family" <- c(sample(letters[1:2], 10, replace = TRUE),rep("a",10))
png("img/networks.png",width=1800,height=600)
p1<-ggnet2(n,mode="circle",color="family",edge.color="blue",size=15,edge.size=2) + scale_color_brewer(palette="Set2") + theme(legend.position = "none")
n <- network(rgraph(15, tprob = 0.3), directed = FALSE)
set.seed(1)
##n %v% "family" <- c(sample(letters[1:2], 10, replace = TRUE),rep("a",10))
p2<-ggnet2(n,mode="circle",color="family",edge.color="red",size=15,edge.size=2) + scale_color_brewer(palette="Set2") + theme(legend.position = "none")
n <- network(rgraph(15, tprob = 0.05), directed = FALSE)
set.seed(1)
##n %v% "family" <- c(sample(letters[1:2], 10, replace = TRUE),rep("a",10))
p3<-ggnet2(n,mode="circle",color="family",edge.color="purple",size=15,edge.size=2) + scale_color_brewer(palette="Set2") + theme(legend.position = "none")
plot_grid(p1,p2,p3,ncol=3,scale = 0.8)
dev.off()

png("img/network_consensus.png",width=600,height=600)
n <- network(rgraph(15, tprob = 0.4), directed = FALSE)
set.seed(1)
##n %v% "family" <- c(sample(letters[1:2], 10, replace = TRUE),rep("a",10))
ggnet2(n,mode="circle",color="family",edge.color="black",size=15,edge.size=2) + scale_color_brewer(palette="Set2") + theme(legend.position = "none")
dev.off()

png("img/network_small.png",width=600,height=600)
n <- network(rgraph(8, tprob = 0.5), directed = FALSE)
set.seed(1)
##n %v% "family" <- c(sample(letters[1:2], 10, replace = TRUE),rep("a",10))
ggnet2(n,mode="circle",color="family",edge.color="black",size=15,edge.size=2) + scale_color_brewer(palette="Set2") + theme(legend.position = "none")
dev.off()

png("img/network_null.png",width=600,height=600)
n <- network(rgraph(15, tprob = 0), directed = FALSE)
set.seed(1)
##n %v% "family" <- c(sample(letters[1:2], 10, replace = TRUE),rep("a",10))
ggnet2(n,mode="circle",color="family",edge.color="black",size=15,edge.size=2) + scale_color_brewer(palette="Set2") + theme(legend.position = "none")
dev.off()


png("img/network_topology.png",width=1200,height=1200)
n <- network(rgraph(100, tprob = .3), directed = FALSE)
set.seed(1)
n %v% "family" <- c(sample(letters[1:2], 100, replace = TRUE,prob=c(.9,.1)),rep("a",100))
ggnet2(n,color="family",size=15,edge.size=.2) + scale_color_brewer(palette="Set2") + theme(legend.position = "none")
dev.off()
